# Homework 4 - Naiara Alonso Montes

## Problem 1

### *Check if a binary linear $[16,5]$-code with $d_{min} = 8$ satisfies the Griesmer bound.*

We are working with a *Reed-Muller* code.
* $n = 16$
* $k = 5$
* $d_{min} = 8$
* $m = 4$
* $r = 1$

$$n = ∑_0^{k - 1}⌈\frac{d_{min}}{2^i}⌉ = $$
$$16 = ⌈\frac{8}{2^0}⌉ + ⌈\frac{8}{2^1}⌉ + ⌈\frac{8}{2^2}⌉ + ⌈\frac{8}{2^3}⌉ + ⌈\frac{8}{2^4}⌉$$

The provided code satisfies the Griesmer bound.

### *Construct a generator matrix of the $[16,5]$-code with $d_{min} = 8$*

The generator matrix is constructed by evaluating these polynomials at all points in $𝔽^2_4$. First we need to get all binary information set of length $=4$.

In [ ]:
import numpy as np

def generate_information_set(length):
    num_combinations = 2**length
    information_set = []
    for i in range(num_combinations):
      binary_string = bin(i)[2:].zfill(length)  # Convert to binary and pad with zeros
      binary_list = [int(bit) for bit in binary_string]  # Convert to a list of ints
      information_set.append(binary_list)
    return np.array(information_set)

print(generate_information_set(4))

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]


Now, with all information sets, we need $k$ polynomial, with one of them being constant, and the others $x_1, x_2, x_3, x_4$.

The generator matrix $G$ looks as follow:

\begin{equation}
G=
\begin{pmatrix}
1\\
\text{1 if 1 in position 1 of information set, 0 otherwise}\\
\text{1 if 1 in position 2 of information set, 0 otherwise}\\
\text{1 if 1 in position 3 of information set, 0 otherwise}\\
\text{1 if 1 in position 4 of information set, 0 otherwise}\\
\end{pmatrix}
\end{equation}
\begin{equation}G =
\begin{pmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 \\
0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\
\end{pmatrix}
\end{equation}



###  *Let $n = 33$, $k = 19$. Use known non-asymptotic bounds in order to determine the range of possible values of the minimum distance.*


#### Hamming bound
$$d_H = ∑_{i = 0}^{⌊\frac{d - 1}{2}⌋}\binom{n}{i}(q - 1)^i≤q^{n - k}$$

* $d = 0$; $d_H = 0$
* $d = 1$; $d_H = 1$
* $d = 2$; $d_H = 1$
* $d = 3$; $d_H = 34$
* $d = 4$; $d_H = 34$
* $d = 5$; $d_H = 562$
* $d = 6$; $d_H = 562$
* $d = 7$; $d_H = 6018$
* $d = 8$; $d_H = 6018$
* $d = 1 > q^{n - k}$

$$d_H = 7; \text{ }d_{min}≤7$$

#### Singleton bound
$$d_S ≤ n - k + 1$$
$$d_S ≤15$$

#### Gilbert-Varshamov bound
$$d_{GV} = ∑_{i = 0}^{d - 2}\binom{n - 1}{i}(q - 1)^i≤q^{n - k}$$
* $d = 0$; $d_{GV} = 0$
* $d = 1$; $d_{GV} = 0$
* $d = 2$; $d_{GV} = 1$
* $d = 3$; $d_{GV} = 33$
* $d = 4$; $d_{GV} = 529$
* $d = 5$; $d_{GV} = 5489$
* $d = 6 > q^{n - k}$

$$d_{GV} = 5; \text{ }d_{min}≤5$$

It turns into lower bound

#### Solution

$$6\le d_{min}\le7$$
The lower bound is 6 and the upper bound is 7. The results obtained in [www.codetables.de/](https://www.codetables.de/) are the same.

## Problem 2


### *A BCH code of length 31 correcting 2 errors is used for transmitting messages. The primitive polynomial $p(x) = x^5 + x^2 + 1$ was used for constructing the code. At the output of the BSC we observe the sequence $y = 0101000001110101010011001111000$ (the smallest degree is the first). Find the decoded codeword by using the Peterson-Gorenstein-Zierler algorithm.*

**Some code parameters**
* $d = 2t + 1 = 5$
* $b(x) = x^{27} + x^{26} + x^{25} + x^{24} + x^{21} + x^{20} + x^{17} + x^{15} + x^{13} + x^{11} + x^{10} + x^{9} + x^{3} + x$
* $s_1 = b(α) = α^{27} + α^{26} + α^{25} + α^{24} + α^{24} + α^{21} + α^{20} + α^{17} + α^{15} + α^{13} + α^{11} + α^{10} + α^{9} + α^{3} + α = α^{25}$
* $s_2 = b(α^2) = s_1^2 = α^{19}$
$s_1 = b(α^3) = α^{19} + α^{16} + α^{13} + α^{10} + α^{} + α^{29} + α^{20} + α^{14} + α^{8} + α^{2} + α^{30} + α^{27} + α^{9} + α^{3} = α^{3}$
* $s_4 = b(α^4) = s_2^2 = α^{7}$

**Algorithm**

\begin{equation}
\begin{pmatrix}
s_1 & s_2\\
s_2 & s_3
\end{pmatrix}
\begin{pmatrix}
Λ_2\\
Λ_1
\end{pmatrix}
=
\begin{pmatrix}
-s_3\\
-s_4
\end{pmatrix}
\end{equation}

$$Δ = α^{28} + α^{7} = α$$

\begin{equation}
Δ_2 =
\begin{vmatrix}
α^{25} & α^{3}\\
α^{19} & α^{7}
\end{vmatrix}
= α + α^{22} = α^{26}
\end{equation}

\begin{equation}
Δ_1 =
\begin{vmatrix}
α^{3} & α^{19}\\
α^{7} & α^{3}
\end{vmatrix}
= α^{6} + α^{22} = α^{14}
\end{equation}

$$Λ_2 = \frac{α^{14}}{α} = α^{13}$$
$$Λ_1 = \frac{α^{26}}{α} = α^{25}$$

$$Λ(x) = 1 + α^{25}x + α^{13}x^2$$

The roots of $Λ(x)$ are $x_1= α^{21}$ and $x_2 = α^{28}$, inverses are $α^{10}$ and $α^{3}$.

\begin{equation}
\begin{pmatrix}
α^{10} & α^{3}\\
α^{20} & α^{6}\\
\end{pmatrix}
\begin{pmatrix}
y_1\\
y_2
\end{pmatrix}
=
\begin{pmatrix}
α^{25}\\
α^{29}\\
\end{pmatrix}
\end{equation}

$$y = α^{10}⋅α^{6} + α^{20}⋅α^{3} = α^{16} + α^{23} = α^{7}$$
\begin{equation}
y_1 =\frac{
\begin{vmatrix}
α^{10} & α^{25}\\
α^{20} & α^{29}
\end{vmatrix}}{α^7}
= \frac{α^{4}}{α^7} = α^{28}
\end{equation}
\begin{equation}
y_2 =\frac{
\begin{vmatrix}
α^{25} & α^{3}\\
α^{29} & α^{6}
\end{vmatrix}}{α^7}
= \frac{α^{18}}{α^7} = α^{11}
\end{equation}

Error values: $α^{28}$ and $α^{11}$

$e(x) = α^{28}x^{21} + α^{11}x^{27}$

$c(x) = b(x) - e(x) = α^{7}x^{27} + x^{26} + x^{25} + x^{24} + \alpha^{7}x^{21} + x^{20} + x^{17} + x^{15} + x^{13} + x^{11} + x^{10} + x^{9} + x^{3} + x$




## Problem 3

### *A BCH code of length 31 correcting 2 errors is used for transmitting messages. The primitive polynomial $p(x) = x^5 + x^2 + 1$ was used for constructing the code. At the output of the BSC we observe the sequence $y = 0101000001110101010011001111000$ (the smallest degree is the first). Find the decoded codeword by using the Berlekamp-Massey algorithm.*

Based on the previous exercise we know:

$$s_1 = b(α) = α^{25}; \text{ }s_2 = b(α^2) = s_1^2 = α^{19}; \text{ }s_3 = b(α^3) = α^{3}; \text{ }s_4 = b(α^4) = s_2^2 = α^{7}$$

**Iter 1**
* $Δ = Λ_0⋅s_1 = 1⋅α^{25} = α^{25}$
* $B(x) = x⋅B(x) = x⋅1 = x$
* $T(x) = Λ(x)+ΔB(x) = 1 + α^{25}x$
* $B(x) = Δ^{-1}Λ(x) = α^{6}⋅1 = α^{6}$
* $L = r - L = 1 - 0 = 1$
* $Λ(x) = T(x) = 1 + α^{25}x$

**Iter 2**
* $Δ = Λ_0⋅s_2 + Λ_1⋅s_1 = 1⋅\alpha^{19} + α^{25}⋅α^{25} = α^{19} + α^{19} = 0$
* $B(x) = x⋅B(x) = x⋅α^{6} = α^{6}x$

**Iter 3**
* $Δ = Λ_0⋅s_3 + Λ_1⋅s_2 = 1⋅α^{3} + α^{25}⋅α^{19} = α^{3} + α^{13} = α^{7}$
* $B(x) = x⋅B(x) = x⋅α^{6}x = α^{6}x^2$
* $T(x) = Λ(x)+ΔB(x) = (1 + α^{25}x) + α^{7}(α^{6}x^2) = 1 + α{25}x + α^{13}x^2$
* $B(x) = Δ^{-1}Λ(x) = α^{24}⋅(1 + α^{25}x) = (α^{24} + α^{18}x)$
* $L = r - L = 3 - 1 = 2$
* $Λ(x) = T(x) = 1 + α{25}x + α^{13}x^2$

**Iter 2**
* $Δ = Λ_0⋅s_4 + Λ_1⋅s_3 + Λ_2⋅s_2 = 1⋅α^{7} + α^{25}⋅α^{3} + α^{13}⋅α^{19} = α^{7} + α^{28} + α = 0$
* $B(x) = x⋅B(x) = x⋅α^{6} = α^{24}x + α^{18}x^2$

|      $r$       |      $Δ$       |        $B(x)$        |       $T(x)$             |                $Λ(x)$       | L |
|-----------------|---------------------------------|-----------------------|-----------------------|----------------------|--------------------|
|$0$|$0$|$1$| |$1$|$0$|
|$1$|$α^{25}$|$α^{6}$|$1 + α^{25}x$|$1 + α^{25}x$|$1$|
|$2$|0|$α^{6}x$|$1 + α^{25}x$|$1 + α^{25}x$|$1$|
|$3$|$α^{7}$|$α^{24} + α^{18}x$|$1 + α^{25}x + α^{13}x^2$|$1 + α^{25}x + α^{13}x^2$|$2$|
|$4$|0|$α^{24}x + α^{18}x^2$|$1 + α^{25}x + α^{13}x^2$|$1 + α^{25}x + α^{13}x^2$|$2$|

$Λ(x) = 1 + α^{25}x + α^{13}x^2$

The obtained $Λ(x)$ is the same, so the result is also the same, error locators are inverses of the roots. Error locators: $α^{21}$, $α^{27}$.

## Problem 4

### *Find the GCD $D$ of two integers $a = 265$ and $b = 95$ by using the Euclidean algorithm.*

### *Find the representation of the found GCD $D = la + jb$, where $l$ and $j$ are integers.*

$$r_0 = a; \text{ }r_1 = b$$
$$x_0 = 1; \text{ }x_1 = 0$$
$$y_0 = 0; \text{ }y_1 = 1$$

$$r_2 = r_0 + q_1⋅r_1 = a - q_1⋅b = 265 - 2 ⋅95 = 75$$
$$x_2 = x_0 + q_1⋅x_1 = 1 - 2⋅0 =1$$
$$y_2 = y_0 + q_1⋅y_1 = 0 - 2⋅1 =-2$$

$$r_3 = r_1 + q_2⋅r_2 = 95 - 1 ⋅75 = 20$$
$$x_3 = x_1 + q_2⋅x_2 = 0 - 1⋅1 =-1$$
$$y_3 = y_1 + q_2⋅y_2 = 1 - 1⋅(-2) =3$$

$$r_4 = r_2 + q_3⋅r_3 = 75 - 3 ⋅20 = 15$$
$$x_4 = x_2 + q_3⋅x_3 = 1 - 3⋅(-1) =4$$
$$y_4 = y_2 + q_3⋅y_3 = -2 - 3⋅3 = -11$$

$$r_5 = r_3 + q_4⋅r_4 = 20 - 1⋅15 = 5$$
$$x_5 = x_3 + q_4⋅x_4 = -1-1⋅4 = -5$$
$$y_5 = y_3 + q_4⋅y_4 = 3-1⋅(-11)=14$$

$$r_6 = r_4 + q_5⋅r_5 = 15 - 3⋅5 = 0$$

#### Solution

$$5 = (-5)⋅256 + 14⋅95$$

### *Find the GCD of two polynomials with coefficients in $GF(5)$, $a(x) = x^3 + x^2 + x + 1$ and $b(x) = x^2 + x +3$*

### *Find the representation of the GCD in the form $l(x)a(x) + j(x)b(x)$ where $l(x)$ and $j(x)$ are polynomial with coefficients in $GF(5)$.*

* $r_0(x) = a(x); \text{ }r_1(x) = b(x)$
* $x_0(x) = 1; \text{ }x_1(x) = 0$
* $y_0(x) = 0; \text{ }y_1(x) = 1$

* $r_2(x) = r_0(x) + q_1(x)⋅r_1(x) = a(x) - q_1(x)⋅b(x) = (x^3 + x^2 + x + 1) - (x)(x^2 + x + 3) = 3x + 1$
* $x_2(x) = x_0(x) + q_1(x)⋅x_1(x) = 1 - (x)⋅0 =1$
* $y_2(x) = y_0(x) + q_1(x)⋅y_1(x) = 0 - (x)⋅1 =4x$

* $r_3(x) = r_1(x) + q_2(x)⋅r_2(x) = (x^2 + x + 3) - (2x)(3x + 1) = 4x + 3$
* $x_3(x) = x_1(x) + q_2(x)⋅x_2(x) = 0 - (2x)(1) = 3x$
* $y_3(x) = y_1(x) + q_2(x)⋅y_2(x) = 1 - (2x)(4x) = 1 - 8x^2 ≡ 1 - 3x^2 ≡ 2x^2 + 1$

* $r_4(x) = r_2(x) + q_3(x)⋅r_3(x) = (3x + 1) - 2(4x + 3) = 0$

#### Solution

$$4x + 3 = 3x(x^3 + x^2 + x + 1) + (2x^2 + 1)(x^2 + x + 3)$$

## *A BCH code of length 32 correcting 1 errors is used for transmitting messages. The primitive polynomial $p(x) = x^5 + x^2 + 1$ was used for constructing the code. At the output of the BSC we observe the sequence $y = 0101000001110101010011001111000$. Find the decoded codeword by using the Euclidean algorithm.*

* $a(x) = x^{2t}≡x^4$
* $b(x) = α^7x^3 + α^3x^2 + α^{19}x + α^{25}$

**Euclidean algorithm, stop condition, degree of $r_n < t$**

* $r_2 = x^4 - (α^7x^3 + α^3x^2 + α^{19}x + α^{25})(α^{24}x + α^{20}) = x^2 + α^{12}x + α^{14}$
* $y_2 = 0 - 1⋅(α^{24}x + α^{20})$

* $r_3 = (α^7x^3 + α^3x^2 + α^{19}x + α^{25}) - (x^2 + α^{12}x + \alpha{14})(α^{7}x + α^{12}) = α^{12}$
* $y_3 = 1 + (α^{24}x + α^{20})(α^{7} + α^{12}) = α^{18} + α^{12}x + x^2 = 1 + α^{25}x + α^{13}x^2$

$Λ(x) = 1 + α^{25}x + α^{13}x^2$

$Ω(x) = α^{12}$

In [9]:
!jupyter nbconvert --to html HW4.ipynb

[NbConvertApp] Converting notebook HW4.ipynb to pdf
[NbConvertApp] Writing 39218 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'notebook.tex', '-quiet']
[NbConvertApp] CRITICAL | xelatex failed: ['xelatex', 'notebook.tex', '-quiet']
b"This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023/Debian) (preloaded format=xelatex)\n restricted \\write18 enabled.\nentering extended mode\n(./notebook.tex\nLaTeX2e <2023-11-01> patch level 1\nL3 programming layer <2024-01-22>\n(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls\nDocument Class: article 2023/05/17 v1.4n Standard LaTeX document class\n(/usr/share/texlive/texmf-dist/tex/latex/base/size11.clo))\n(/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty\n(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty\n(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty\n(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex)\